let suggestions = [
    "Carregar caixas",
    "Movimentação de móveis",
    "Limpeza de terrenos",
    "Serviços de jardinagem",
    "Lavagem de carros",
    "Desentupimento de esgotos",
    "Pintura de paredes",
    "Reparos em telhados",
    "Demolição de estruturas",
    "Montagem de móveis",
    "Corte de grama",
    "Capina de lotes",
    "Limpeza de piscinas",
    "Carregamento de caminhões",
    "Limpeza pós-obra",
    "Recolhimento de entulhos",
    "Mudança residencial",
    "Instalação de cercas",
    "Limpeza de calhas",
    "Corte de árvores",
    "Podar árvores",
    "Limpeza de terrenos baldios",
    "Retirada de lixo",
    "Abertura de valas",
    "Limpeza de garagens",
    "Montagem de estruturas metálicas",
    "Carpintaria básica",
    "Lavagem de fachadas",
    "Limpeza de telhados",
    "Carregamento de materiais de construção",
    "Instalação de pisos",
    "Remoção de entulhos",
    "Pintura de grades",
    "Aparar cercas-vivas",
    "Lavagem de muros",
    "Escavação manual",
    "Transporte de materiais",
    "Serviços de pedreiro",
    "Rebocar paredes",
    "Instalação de drywall",
    "Montagem de andamios",
    "Fixação de painéis solares",
    "Limpeza de porões",
    "Corte de lenha",
    "Arrumação de depósitos",
    "Desmontagem de móveis",
    "Serviços de serralheria",
    "Cuidado de animais de grande porte",
    "Limpeza de fossas",
    "Montagem de barracas",
    "Carregar sacos de cimento",
    "Instalação de janelas",
    "Remoção de neve",
    "Transporte de móveis pesados",
    "Troca de telhas",
    "Remoção de pisos antigos",
    "Instalação de portas",
    "Montagem de tendas",
    "Serviços de eletricista básico",
    "Conserto de cercas",
    "Limpeza de vidros",
    "Escovação de pátios",
    "Limpeza de porões",
    "Pintura de muros",
    "Troca de lâmpadas em locais altos",
    "Carregar pedras",
    "Reparação de calçadas",
    "Corte de galhos altos",
    "Reforma de móveis",
    "Limpeza de sótãos",
    "Serviços de manutenção em playgrounds",
    "Remoção de galhos caídos",
    "Desmonte de estruturas",
    "Ajuste de portas",
    "Serviços de pintura em altura",
    "Corte de bambus",
    "Assentamento de tijolos",
    "Cavamento de buracos para postes",
    "Instalação de grades",
    "Limpeza de ventiladores de teto",
    "Serviços de marcenaria",
    "Reparação de alvenaria",
    "Instalação de prateleiras",
    "Troca de fechaduras",
    "Montagem de estruturas de madeira",
    "Instalação de redes de proteção",
    "Desmontagem de barracas",
    "Montagem de estantes",
    "Limpeza de sistemas de ventilação",
    "Ajuste de móveis",
    "Reparos em drywall",
    "Reforma de telhados",
    "Corte de canos",
    "Fixação de quadros",
    "Instalação de cortinas",
    "Desobstrução de bueiros",
    "Instalação de cercas elétricas",
    "Pintura de estruturas metálicas",
    "Remoção de vegetação indesejada",
    "Serviços de garimpo",
    "Escavação de terrenos",
    "Diarista",
    "Jardineiro",
    "Marceneiro"
];